### ISSUE TITLE
Could you please tell me where is the crossover done?

### ISSUE THREAD

**Issue by yoshitakaF** [huystalker/evolving-reaction-networks#1]
I read the "reproduction" in the "Population.java".
I can not find a place that is running the crossover in the program.
Could you please tell me where you are doing the crossover ?

**Comment by rr-huy-dinh** [comment]
Hi,

You are right. This is the mutation-only version and the crossover is not included. I tried to locate the crossover code from the old repository on [Google code](https://code.google.com/archive/) for you but sadly it was gone since 2016.
By the way, I stopped working on this project since 2015. You'd better contact the other author who is still actively working on this at nathanael.aubert@gmail.com

**Comment by yoshitakaF** [comment]
Thank you for the answer !
I decided to create it myself.
